version: '3'

services:
  node: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
        APPLICATION_PATH: ${APPLICATION_PATH}
    tty: true
    working_dir: /var/www
    volumes:
      - ${APPLICATION_PATH}:/var/www
    environment:
      PORT: ${NUXT_PORT}
      HOST: ${HOST}
    restart: always

  workspace:
    <<: *app_base
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    command: yarn dev

  storybook:
    <<: *app_base
    ports:
      - "${STORY_BOOK_PORT}:${STORY_BOOK_PORT}"
    command: yarn storybook
