version: '3'

services:
  app: &app_base
    image: node:${NODE_VERSION}
    volumes:
      - ${APPLICATION_PATH}:/var/www
      - node_modules:/var/www/node_modules
    environment:
      PORT: ${NUXT_PORT}
      HOST: ${HOST}
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    working_dir: /var/www
    restart: always
    command: yarn dev
    tty: true

  storybook:
    <<: *app_base
    ports:
      - "${STORY_BOOK_PORT}:${STORY_BOOK_PORT}"
    command: yarn storybook

volumes:
  node_modules: