version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        APPLICATION_PATH: ${APPLICATION_PATH}
    tty: true
    working_dir: /var/www
    volumes:
      - "${APPLICATION_PATH}:/var/www"
      - "/var/www/node_modules"
    ports:
      - "${VUE_PORT}:${VUE_PORT}"
    environment:
      PORT: ${VUE_PORT}
      HOST: ${HOST}
    command: yarn serve
    restart: always
